<?php
require_once "includes/header.php";
redirect_if_not_logged_in();

$branches = is_super_admin() ? $conn->query("SELECT id, name FROM branches ORDER BY name") : null;
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/litepicker/dist/css/litepicker.css">

<div class="card">
    <div class="card-header">
        <h3>Manage Invoices</h3>
    </div>
    <div class="card-body">
        <div class="tabs">
            <div class="tab-link active" data-status="completed">Completed</div>
            <div class="tab-link" data-status="pending">Pending</div>
        </div>

        <div class="invoice-filter-controls">
            <div class="filter-row">
                <div class="form-group">
                    <label>Start Date</label>
                    <input type="text" id="start_date" class="form-control" placeholder="YYYY-MM-DD">
                </div>
                <div class="form-group">
                    <label>End Date</label>
                    <input type="text" id="end_date" class="form-control" placeholder="YYYY-MM-DD">
                </div>
                <button id="apply-filter-btn" class="btn btn-primary">Apply Filter</button>
            </div>
            <div class="filter-row">
                <div class="form-group">
                     <label>Search</label>
                    <input type="text" id="ajax-search" class="form-control" placeholder="Search by invoice # or patient name...">
                </div>
                <?php if (is_super_admin()): ?>
                <div class="form-group">
                    <label>Branch</label>
                    <select id="branch_filter" class="form-control">
                        <option value="">All Branches</option>
                        <?php if($branches) { mysqli_data_seek($branches, 0); } while($branches && $branch = $branches->fetch_assoc()): ?>
                            <option value="<?php echo $branch['id']; ?>"><?php echo htmlspecialchars($branch['name']); ?></option>
                        <?php endwhile; ?>
                    </select>
                </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="responsive-table-container">
            <table class="responsive-table">
                <thead id="invoices-table-head">
                    <!-- Header will be dynamically generated by JS -->
                </thead>
                <tbody id="invoices-table-body">
                    <!-- AJAX content will be loaded here -->
                </tbody>
            </table>
        </div>
        <div class="pagination-container" id="pagination-container">
             <!-- AJAX pagination will be loaded here -->
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/litepicker.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const tableHead = document.getElementById('invoices-table-head');
    const tableBody = document.getElementById('invoices-table-body');
    const paginationContainer = document.getElementById('pagination-container');
    const searchInput = document.getElementById('ajax-search');
    const branchFilter = document.getElementById('branch_filter');
    const applyFilterBtn = document.getElementById('apply-filter-btn');
    const tabs = document.querySelectorAll('.tab-link');
    const startDateInput = document.getElementById('start_date');
    const endDateInput = document.getElementById('end_date');
    let currentStatus = 'completed';

    new Litepicker({ element: startDateInput, format: 'YYYY-MM-DD' });
    new Litepicker({ element: endDateInput, format: 'YYYY-MM-DD' });

    function setTableHeader() {
        const isSuperAdmin = <?php echo is_super_admin() ? 'true' : 'false'; ?>;
        let headerHtml = '<tr><th>Invoice #</th><th>Patient</th><th>Total Amount</th><th>Amount Paid</th>';
        if (currentStatus === 'pending') {
            headerHtml += '<th>Balance Due</th>';
        }
        headerHtml += '<th>Date</th>';
        if (isSuperAdmin) {
            headerHtml += '<th>Branch</th>';
        }
        headerHtml += '<th>Actions</th></tr>';
        tableHead.innerHTML = headerHtml;
    }

    function loadInvoices(page = 1) {
        const query = searchInput.value;
        const branchId = branchFilter ? branchFilter.value : '';
        const startDate = startDateInput.value;
        const endDate = endDateInput.value;
        const colspan = tableHead.querySelector('tr').children.length;

        tableBody.classList.add('loading');

        const url = `ajax_search.php?page=invoices&status=${currentStatus}&query=${encodeURIComponent(query)}&branch_id=${encodeURIComponent(branchId)}&start_date=${encodeURIComponent(startDate)}&end_date=${encodeURIComponent(endDate)}&p=${page}`;

        fetch(url)
            .then(response => response.json())
            .then(data => {
                if (data && data.table_html) {
                    tableBody.innerHTML = data.table_html;
                } else {
                    tableBody.innerHTML = `<tr><td colspan="${colspan}" class="text-center">No invoices found.</td></tr>`;
                }
                if (data && data.pagination_html) {
                    paginationContainer.innerHTML = data.pagination_html;
                } else {
                    paginationContainer.innerHTML = '';
                }
            })
            .catch(error => {
                console.error('Error fetching invoice data:', error);
                tableBody.innerHTML = `<tr><td colspan="${colspan}" class="text-center">An error occurred. Please try again.</td></tr>`;
            })
            .finally(() => {
                tableBody.classList.remove('loading');
            });
    }
    
    tabs.forEach(tab => {
        tab.addEventListener('click', function() {
            tabs.forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            currentStatus = this.dataset.status;
            setTableHeader();
            loadInvoices(1);
        });
    });

    let searchTimeout;
    searchInput.addEventListener('keyup', function() {
        clearTimeout(searchTimeout);
        searchTimeout = setTimeout(() => {
            loadInvoices(1);
        }, 300);
    });
    
    if (branchFilter) {
        branchFilter.addEventListener('change', () => loadInvoices(1));
    }
    applyFilterBtn.addEventListener('click', () => loadInvoices(1));

    paginationContainer.addEventListener('click', function(e) {
        if (e.target.matches('a.page-link')) {
            e.preventDefault();
            const page = e.target.dataset.page;
            if (page) {
                loadInvoices(page);
            }
        }
    });
    
    tableBody.addEventListener('click', function(e) {
        if (e.target.classList.contains('mark-complete-btn')) {
            const invoiceId = e.target.dataset.id;
            if (confirm('Are you sure you want to mark this invoice as complete?')) {
                fetch(`update_invoice_status.php?id=${invoiceId}`, { method: 'POST' })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            loadInvoices(1);
                        } else {
                            alert('Failed to update status: ' + (data.error || 'Unknown error'));
                        }
                    });
            }
        }
    });

    setTableHeader();
    loadInvoices(1);
});
</script>

<?php require_once "includes/footer.php"; ?>

